### ISSUE TITLE
Infracost summary not added to PR comment

### ISSUE THREAD

**Issue by BFarand** [cloudposse/github-action-atmos-terraform-plan#98]
### Describe the Bug

When `pr-comment` is set to `true` and Infracost is enabled (in atmos configuration and `infracost-api-key is provided`), the `%INFRACOST_SUMMARY%` and `%INFRACOST_DIFF%` placeholders are not replaced in the comment made in the pull request.

Note that the Infracost summary is added successfully to the GitHub action summary, so the results can still be viewed there. It is only missing from the PR comment.

From what I can tell, the PR comment is made as part of the tfcmt commands. The job step that replaces the Infracost placeholders, `Set Infracost Variables`, runs _after_ the tfcmt commands, so the Infracost variables are not available in time for tfcmt. This is a bit of an interesting problem as tfcmt is also responsible for running the plan, which is required by Infracost.

### Expected Behavior

The PR comment should match nearly/exactly 1:1 with the GitHub action summary. The `%INFRACOST_SUMMARY%` and `%INFRACOST_DIFF%` placeholders should be properly replaced.

### Steps to Reproduce

1. Ensure `integrations.github.gitops.infracost-enabled` is set to `true` in atmos configuration.
2. In the workflow, ensure `infracost-api-key` is provided and `pr-comment` is set to `true`.
3. Run the workflow (preferably with an expected change).
4. Observe the PR comment result.

### Environment

- Version `4.3.0` of this action (digest `1694fc56284f79173c36922f869933c6cb1d8b72`)

**Comment by BFarand** [comment]
Until a solution for this solution is proposed and merged in, here is 'patch' solution that I came up with in the meantime.

After using this action as normal (assuming it is being used in response to a PR, as demonstrated in the docs of this action):

```yaml
- name: "Find existing PR comment"
  id: "find-pr-comment"
  uses: peter-evans/find-comment@v3
  with:
    comment-author: 'github-actions[bot]'
    body-includes: ${{ matrix.stack_slug }}
    issue-number: ${{ github.event.pull_request.number }}

- name: "Generate new PR comment"
  id: "generate-pr-comment-body"
  if: steps.find-pr-comment.outputs.comment-id != ''
  shell: bash
  env:
    EXISTING_PR_COMMENT: ${{ steps.find-pr-comment.outputs.comment-body }}
  run: |
    INFRACOST_DIFF_TOTAL_MONTHLY_COST=$(cat /tmp/infracost.json | jq --raw-output .diffTotalMonthlyCost)
    INFRACOST_DETAILS_DIFF_BREAKDOWN="$(cat /tmp/infracost.txt)"

    if [[ "${INFRACOST_DIFF_TOTAL_MONTHLY_COST}" == "0" ]]; then
      INFRA_COST_SUMMARY="Infracost Estimate: monthly cost will not change"
    elif [[ "${INFRACOST_DIFF_TOTAL_MONTHLY_COST:0:1}" == "-" ]]; then
      INFRA_COST_SUMMARY="Infracost Estimate: monthly cost will decrease by ${INFRACOST_DIFF_TOTAL_MONTHLY_COST} 📉"
    else
      INFRA_COST_SUMMARY="Infracost Estimate: monthly cost will increase by ${INFRACOST_DIFF_TOTAL_MONTHLY_COST} 📈"
    fi

    {
      echo 'pr-comment-body<<EOF'
      echo "$EXISTING_PR_COMMENT" | sed "s/%INFRACOST_SUMMARY%/${INFRA_COST_SUMMARY}/" | sed -e '/%INFRACOST_DIFF%/{r /tmp/infracost.txt' -e 'd}'
      echo EOF
    } >> "$GITHUB_OUTPUT"

- name: "Patch existing PR comment"
  if: steps.find-pr-comment.outputs.comment-id != ''
  uses: peter-evans/create-or-update-comment@v4
  with:
    comment-id: ${{ steps.find-pr-comment.outputs.comment-id }}
    edit-mode: "replace"
    body: "${{ steps.generate-pr-comment-body.outputs.pr-comment-body }}"
```

How it works:

- PR comment is initially made by this action, with the existing InfraCost placeholders
- We find the PR comment by looking for one made by the github-actions user containing the stack slug
  - If multiple comments are made for the same stack slug, this would always just take the first comment. I don't think this should happen though...
- We patch the existing PR comment by using the existing comment body, then use sed to replace the placeholders in question.
  - All of the InfraCost variables etc. are copied straight from the action source - the 'unique' part is everything in the curly braces at the end, really.
  - Generating this new PR comment body in a separate step is probably overkill - I did it this way as I also wanted to append trivy scan results to it.
- The existing PR comment is then updated, being entirely replaced with the new PR body.

A few other notes:
- Every time this action runs, it will 'reset' the PR comment back to containing the placeholders before this extra bit does the patch, so you get some flapping behaviour. 
- This action doesn't expose any InfraCost variables as output, which is why I had to duplicate that stuff. InfraCost itself doesn't actually run again, though.
- Using $GITHUB_STEP_SUMMARY and just making it the PR comment doesn't work as it will always be blank (it is per step).
- Using the summary output of this action also didn't work nicely as it isn't properly formatted. That is why I use the comment-body from the find-comment action.

Hopefully this is useful to someone else, or provides some potential ideas for updating the action itself!
